import type { Metadata } from 'next'
import './globals.css'
import ClientTransition from './ClientTransition'
import ResponsiveNavbar from './ResponsiveNavbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-gray-50 dark:bg-neutral-900 text-black dark:text-white">
        <ResponsiveNavbar />
        <ClientTransition>{children}</ClientTransition>
      </body>
    </html>
  )
}
